### ISSUE TITLE
Teardrops suppressed by high priority zones

### ISSUE THREAD

**Issue by StefanHamminga** [NilujePerchut/kicad_scripts#1]
Currently the script doesn't seem to add a zone priority to the created teardrop zones. This causes the teardrops of tracks running through higher than zero priority zones to be suppressed.

Adding `z.SetPriority(127)` to line 86 of the script fixes the issue. Note that I picked a randomly high number (the highest signed int value), I haven't looked what the actual limit is.

**Comment by NilujePerchut** [comment]
I totally forgot this zone property.
I just applied the zone priority as you've suggested.

Thank you very much.
