### ISSUE TITLE
Teardrops fail when three traces go to via

### ISSUE THREAD

**Issue by aaronw2** [NilujePerchut/kicad_scripts#12]
When I have three traces going to a via but the teardrops only not created for all of the traces. In the below image, only one of the front traces (going to the right) has a teardrop.
![image](https://user-images.githubusercontent.com/13844499/68868089-be4b4680-06ab-11ea-8f05-74cdaa40171c.png)
Here is another via with only one teardrop.
![image](https://user-images.githubusercontent.com/13844499/68868242-0bc7b380-06ac-11ea-969a-fa03bd1c14da.png)
Note that the teardrops are visible in the gerber view.

Kicad version 5.1.4
wxWidgets 3.0.3

**Comment by NilujePerchut** [comment]
If teardrops are visible in the gerber files, I suspect that the missing one is created but not displayed.
This is a known bug which should have been corrected by  #9 .
I will check I can figure out why it is not working for all layers.
Meanwhile, you should be able to make them visible by saving the pcb project and reopen it.

**Comment by aaronw2** [comment]
Saving and quitting and reloading didn't work. I suspect it is a Kicad bug
since sometimes I see them all then they disapear.

-Aaron

**Comment by NilujePerchut** [comment]
I think you are right, it seems like it is a Kicad bug.
I will close this issue, but feel free to re-open it if you have news about it.
