### ISSUE TITLE
Teardrops in zones (ground planes)

### ISSUE THREAD

**Issue by tmanaud** [NilujePerchut/kicad_scripts#18]
There is an issue with via with tracks on planes with copper pour.  

Sample with copper pour and vias without teardrops: expected copper pour fill:
![via_on_gnd_plane_without_teardrops](https://user-images.githubusercontent.com/265371/78649718-1cc4cb80-78be-11ea-84cb-af9358aa9c38.png)

Sample with copper pour and vias with teardrops applied: prevents copper pour
![via_on_gnd_plane_with_teardrop](https://user-images.githubusercontent.com/265371/78649717-1c2c3500-78be-11ea-9d98-3b6619e240ca.png)

Note: ground stitching has to be attached with tracks, not just vias otherwise it just create via "island" on the next zone refill.  
Suggested solution: do not place teardrops if via are inside area/copper pour.  

Application: Pcbnew
Version: 5.1.5-52549c5~86~ubuntu19.04.1, release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.6/openssl/zlib nghttp2/1.36.0 librtmp/2.3
Platform: Linux 5.0.0-38-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
    Boost: 1.67.0
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.64.0
    Compiler: GCC 8.3.0 with C++ ABI 1013

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

**Comment by NilujePerchut** [comment]
Hi,
I tried to reproduce your problem without success.
Is it possible for you to send me the .kicad_pcb file for me to check ?
Thanks in advance.

**Comment by tmanaud** [comment]
Hello NilujePerchut, thanks for taking time to look into this issue.  

Sure, here is the .kicad_pcb file zipped:
[pcb_test.kicad_pcb.zip](https://github.com/NilujePerchut/kicad_scripts/files/4464289/pcb_test.kicad_pcb.zip)

When reproducing the issue, I found out two parts:
- teardrops are created inside ground/area
- when area are filled, with teardrop/via close to area side, it fails.
![image](https://user-images.githubusercontent.com/265371/79039624-d2f02400-7be2-11ea-9842-d75c74284907.png)

Feel free to ask if I can help you in any way.

**Comment by NilujePerchut** [comment]
This should be fixed now (v0.4.8). 
I added and option (true by default) to keep the possibility to restore the original behaviour.
This might be useful in the following cases:
1) This new option might slow the process down
2) The behaviour is not defined if multiple zone overlap

Please, test it and let me know.
If it is ok for you, I will close the issue.

**Comment by tmanaud** [comment]
Wow, that was an ultra quick fix!
Fixed it on my side:
![image](https://user-images.githubusercontent.com/265371/79102507-2a210080-7d6b-11ea-9d97-98dec98a5725.png)

Thanks a lot!
