### ISSUE TITLE
Teardrop issue in inner layers : Extra teardrops being added in inner layers

### ISSUE THREAD

**Issue by chirag070** [NilujePerchut/kicad_scripts#20]
Hello There,
Thanks for making this wonderful plugin available for everyone. It helps a lot. I have observed one issue as described below.

When tracks are routed in inner layer which are beneath the SMD pads of Top/Bottom layers, The plugin generates teardrops in inner layer. Here are the screenshots and KiCAD project file attached.

![tear_1](https://user-images.githubusercontent.com/10007963/82181595-78906480-9900-11ea-896a-b663de51448a.png)

![tear_2](https://user-images.githubusercontent.com/10007963/82181615-80500900-9900-11ea-844f-d64a3f1b1aae.png)

[teardrop_kicad_files.zip](https://github.com/NilujePerchut/kicad_scripts/files/4642404/teardrop_kicad_files.zip)

KiCAD Version : Stable 5.1.5_3, Windows, 64bit
Plugin Version : 0.4.8

![version](https://user-images.githubusercontent.com/10007963/82181651-8e9e2500-9900-11ea-95aa-aab6f4b3dbf2.png)

**Comment by NilujePerchut** [comment]
Hi,
Thanks for such a detailed report.
I will fix that as soon as possible.

**Comment by NilujePerchut** [comment]
Hi,
Sorry for the delay.
Can you confirm that commit 0bcbbc377f2a5a13c646d1fc5ed16993f87a8f73 fixes you problem ?
Thanks in advance.

**Comment by chirag070** [comment]
Hello,
Yes. v0.4.9 solved the issue. Thanks a lot.
![20_solved](https://user-images.githubusercontent.com/10007963/83935254-889bb580-a7d5-11ea-8b8f-7eab6f79099c.jpg)
