### ISSUE TITLE
teardrop plugin dialog buttons have no effect

### ISSUE THREAD

**Issue by itsnoteasy** [NilujePerchut/kicad_scripts#22]
i'm running kicad nightly as root. remove all teardrops operates normally on a pcb with teardrops, set teardrops does nothing.

**Comment by NilujePerchut** [comment]
Sorry for this answer.
This repo is dedicated to Kicad stable version.
I had to many compatibility breaks to handle during the 4.99 cycle and I do not want do the same during the 5.99 one.
However, I will try to see if a small fix is possible. If yes, I will probably create a 5.99 branch to implement it.

I am really looking forward to see such feature implemented by default inside Kicad.

**Comment by NilujePerchut** [comment]
Now working in V6

**Comment by itsnoteasy** [comment]
awesome, thanks
