### ISSUE TITLE
About teardrop plug-in update to kicad_ V5.99

### ISSUE THREAD

**Issue by xiaotaomcu** [NilujePerchut/kicad_scripts#31]
My friend, your plug-in is easy to use, but it doesn't support v5.99. Do you have time to update the plug-in? Thank you very much

**Comment by NilujePerchut** [comment]
This will ported to 5.99 as soon as the Kicad python API is stabilized.

**Comment by xiaotaomcu** [comment]
okay, thank you

**Comment by easyw** [comment]
it seems it has been patched for k v5.99
https://github.com/beanjs-kicad/beantools/tree/master/beantools/teardrops
it would be nice to have it merged or merged in a dev branch

**Comment by NilujePerchut** [comment]
All 5.99/6_RC1 porting issues are now using the same #35 thread.

**Comment by NilujePerchut** [comment]
Hi all,
Please try the V5.99_V6RC branch based on beanjs work.
This was successfully (but quickly) tested on a board of mine (kicad-git/archlinux (V6RC)).
Let me know if you have any comment/bugs
