### ISSUE TITLE
Bump to kicad 7 and implement some features from the fork

### ISSUE THREAD

**Issue by regicidalplutophage** [NilujePerchut/kicad_scripts#47]
Hi! Sorry to bother you and thanks for such a great tool.

Native implementation of teardrops in kicad 7 leaves a lot to be desires and for round pads this plugin with "prevent eccentric teardrops from bulging outwards" unchecked produces the best results.

There's also a [fork](https://github.com/GameWithPixels/Kicad_Teardrops). A lot of the times it produces impressive results with rectangular pads, but all logic has been re-written and "prevent eccentric teardrops from bulging outwards" box does nothing. Also, sometimes it produces weird results where a teardrop is thinner than the track.

So, a near perfect plugin would apply current logic to round pads, logic from the fork to every other kind, fix some edge cases and it would run in kicad 7.0 which as I understand is harder to do than bumping from 5.0 to 6.0.

I understand that it hasn't been touched in quite some time, but I'd like to ask you to please continue development.

**Comment by NilujePerchut** [comment]
Hi, since Kicad already includes teardrop supports since V7, I recommend to use it.
This repo won't be updated anymore.
