### ISSUE TITLE
Kicad exception

### ISSUE THREAD

**Issue by leoheck** [NilujePerchut/kicad_scripts#5]
Hi @NilujePerchut I am receiving the following exception when opening the PcbNew on Kicad.

![Screenshot-20190506213025-723x294_action_script_kicad_issue](https://user-images.githubusercontent.com/1277920/57302961-b3877780-70b2-11e9-8da7-111af82da80c.png)

I've created a bug report for Kicad devs.

But it is possible that teardrop plugin is causing this exception because I have only one plugin.

I am using Kicad `Version: 5.1.2-f72e74a~84~ubuntu19.04.1, release build`

https://bugs.launchpad.net/kicad/+bug/1826493

Do you know what should I do to investigate this better?

**Comment by NilujePerchut** [comment]
Hi @leoheck,
I do not think this is coming from my plugin. Nevertheless, I do not have a lot of experience with the python3 version, this could be something I missed.
I noticed you are using Ubuntu 19.04.1, it might be related to it. Did you try on another version of Ubuntu ?
Are you getting the same problem without any plugin at all ?
I just released a new version (2.4.4), even if this should not have any influence on it, can you try it ?

**Comment by leoheck** [comment]
Hello, @NilujePerchut I don't have this issue very often but I don't know it is related to your plugin. I will install the new version to monitor if this happens again. Thank you for the feedback.

**Comment by NilujePerchut** [comment]
Hello @leoheck , I would like to close this issue.
Do you have any news about it ?

**Comment by leoheck** [comment]
Hello, @NilujePerchut I think I am good. I will do it for you, right?
